### ISSUE TITLE
Create the one-/two-/three-dimensional line groups with the help of this package based on the Orbifold/Schönflies/Conway/Coxeter notations.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#100]
Hi here,

I noticed some examples of line groups given [here](https://en.wikipedia.org/wiki/Line_group), as shown below:

![image](https://user-images.githubusercontent.com/11155854/209745728-057a91b3-f242-4cf3-bfa7-9668e3467e19.png)
![image](https://user-images.githubusercontent.com/11155854/209745772-9e524466-3070-457d-b825-b4a847f8ab3f.png)
![image](https://user-images.githubusercontent.com/11155854/209745812-eafa7bea-c08e-4819-8bd8-8808bf978bac.png)

I'm not sure whether it's possible for me to create these one-/two-/three-dimensional line groups with the help of **HAP** package based on the `Orbifold/Schönflies/Conway/Coxeter` notations given above?

Any tips will be appreciated.

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
I don't think there is anything in HAP that would help with this. But I guess it should be possible using core GAP commands.

**Comment by hongyi-zhao** [comment]
Thank you for your comments and reply. The difficulty is that it is quite difficult to figure out which commands to use.
