### ISSUE TITLE
Check whether an infinite group is non-nilpotent quickly with the help of HAP.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#103]
I want to check all the infinite non-nilpotent groups in 4-d space groups. The method I use is as follows and it is very slow:

```gap
for i in [1..4783] do
  s:=SpaceGroup(4,i);
  if IsSolvable(s) then
    pcp:=Image(IsomorphismPcpGroup(s));
    if IsNilpotent(pcp) then
      Print(i,"\n");
    else 
      Print(i, " N","\n");  
    fi;
  fi;
od;
```
So, I wonder whether there are some more fast methods to do this with the help of HAP. Any tips will be appreciated.

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
There is nothing in HAP which would improve on:

`gap> G:=SpaceGroup(4,3000);;IsPolycyclicGroup(G);IsNilpotent(Range(IsomorphismPcpGroup(G)));time;
true
false
124`

**Comment by hongyi-zhao** [comment]
Your code snippet does not use any specific HAP functions, so what do you mean?
```gap
gap> G:=SpaceGroup(4,3000);;
gap> IsPolycyclicGroup(G);; time;
106
gap> IsNilpotent(Image(IsomorphismPcpGroup(G)));; time;
157
gap> IsNilpotent(Range(IsomorphismPcpGroup(G)));; time;
1
```

**Comment by grahamknockillaree** [comment]
I mean that there is **nothing in HAP** which would improve on those commands from other packages.

**Comment by hongyi-zhao** [comment]
I see.
