### ISSUE TITLE
bug in `StemGroups`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/hap#105]
The following example occurs in one of hap's testfiles.
```
gap> G:=SmallGroup(8,5);;
gap> Set(List(StemGroups(G),IdGroup));
[ [ 32, 28 ], [ 64, 73 ] ]
```
When I run this input several times then I get sometimes the different result `[ [ 32, 27 ], [ 64, 73 ] ]`.
This happens both with GAP 4.12.2 and with the master branch of GAP.

(I had observed this when investigating the problem from issue #104.
It took me some time until I understood that the different results are not caused by recent changes to the GAP master branch.)

**Comment by fingolfin** [comment]
Yeah the stem groups are only well-defined up to isoclinism... Actually that test cost us trouble before. It should be made more resilient.

**Comment by grahamknockillaree** [comment]
In HAP v1.49 or earlier this test was changed to

gap> G:=SmallGroup(8,5);;
gap> Size(List(StemGroups(G),IdGroup));
2

But there is no point in any HAP test running StenGroup() as it is not part of HAP so I'll delete the test from future releases.

Apologies for the troubles.
Graham

**Comment by fingolfin** [comment]
Huh? `StemGroups` is defined in `lib/NonabelianTensor/equivalenceclasses.gi`

**Comment by grahamknockillaree** [comment]
Oops! You are right.
