### ISSUE TITLE
Retrieve the list of exact cocycle vectors generated by the HAP package and the preimage of GOuterGroup.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#110]
Let us re-consider the problem discussed [here](https://github.com/gap-packages/hap/issues/72#issuecomment-1172881649):

```gap
gap> LoadPackage("hap");
true
gap> M1:=[[0,0,1,1/4],[1,0,0,1/4],[0,-1,0,1/4],[0,0,0,1]];;
gap> M2:=[[0,0,-1,0],[0,-1,0,0],[1,0,0,0],[0,0,0,1]];;
gap> S:=AffineCrystGroupOnLeft([M1,M2]);;
gap> S:=Image(IsomorphismPcpGroup(S));;
gap> IsAlmostCrystallographic(S);;
gap> T:=Kernel(NaturalHomomorphismOnHolonomyGroup(S));;
gap> OT := GOuterGroup(S,T);;
gap> P:=ActingGroup(OT);;
gap> R:=ResolutionFiniteGroup(P,3);;
gap> C:=HomToGModule(R,OT);;
gap> CH:=CohomologyModule(C,2);;
Elts:=Elements(ActedGroup(CH));;
lst := List(Elts{[1..Length(Elts)]},x->CH!.representativeCocycle(x));
gap> Elts:=Elements(ActedGroup(CH));;
gap> lst := List(Elts{[1..Length(Elts)]},x->CH!.representativeCocycle(x));
[ Standard 2-cocycle 
    , Standard 2-cocycle 
    , Standard 2-cocycle 
    , Standard 2-cocycle 
     ]
```
Here, I've the following questions:

1. How to obtain the list of exact cocycle vectors stored in `lst`?
2. How to obtain the preimage of `OT`, aka, in its matrix representation as the subgroup of S?

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
Hi,

gap> M1:=[[0,0,1,1/4],[1,0,0,1/4],[0,-1,0,1/4],[0,0,0,1]];;
gap> M2:=[[0,0,-1,0],[0,-1,0,0],[1,0,0,0],[0,0,0,1]];;
gap> SS:=AffineCrystGroupOnLeft([M1,M2]);;
gap> iso:=IsomorphismPcpGroup(SS);;
gap> S:=Image(iso);;
gap> IsAlmostCrystallographic(S);;
gap> T:=Kernel(NaturalHomomorphismOnHolonomyGroup(S));;
gap> OT := GOuterGroup(S,T);;
gap> P:=ActingGroup(OT);;
gap> R:=ResolutionFiniteGroup(P,3);;
gap> C:=HomToGModule(R,OT);;
gap> CH:=CohomologyModule(C,2);;
gap> Elts:=Elements(ActedGroup(CH));;
gap> lst := List(Elts{[1..Length(Elts)]},x->CH!.representativeCocycle(x));;

A standard 2-cocycle is a function G:P x P ---> T. The function f can be evaluated as follows.

gap> f:=lst[1]!.Mapping;;
gap> g:=Random(P);;
gap> h:=Random(P);;
gap> f(g,h);
g6^2*g7^-1*g8^-1


Matrix generators for the group T can be found as follows.

gap> PreImagesSet(iso,GeneratorsOfGroup(T));
[ [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 1 ], [ 0, 0, 0, 1 ] ],
  [ [ 1, 0, 0, 0 ], [ 0, 1, 0, 1/2 ], [ 0, 0, 1, 1/2 ], [ 0, 0, 0, 1 ] ],
  [ [ 1, 0, 0, 1/2 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 1/2 ], [ 0, 0, 0, 1 ] ] ]


Hope this helps.

Graham

**Comment by hongyi-zhao** [comment]
But this method doesn't work with `IsomorphismFpGroup`, as shown below:
```gap
gap> iso:=IsomorphismFpGroup(SS);;
gap> S:=Image(iso);
<fp group on the generators [ f1, f2, f3, f4, f5, f6, f7, f8 ]>
gap> IsAlmostCrystallographic(S);
sorry - cannot check this property 
Error, Method for a property did not return true or false
not in any function at *stdin*:48
type 'quit;' to quit to outer loop
brk> 
```
So, this method will not work with nonsolvable groups. Is there an alternative solution to tackle the case of nonsolvable groups?

**Comment by grahamknockillaree** [comment]
I know of no method for testing if a general fp group is almost crystallographic. Remember that there is no algorithm for deciding if an arbitrary fp group is the trivial group or not.

As for the output you list, \I have no idea what it means.

**Comment by hongyi-zhao** [comment]
> As for the output you list, \I have no idea what it means.

It should be the translational part expressed as a vector system, aka, 1-cocycle of the 1-cohomology group H^1(G,Q^n/Z^n).

I tried as follows to obtain them, but still in vain:

```gap
gap> LoadPackage("hap");;
gap> M1:=[[0,0,1,1/4],[1,0,0,1/4],[0,-1,0,1/4],[0,0,0,1]];;
gap> M2:=[[0,0,-1,0],[0,-1,0,0],[1,0,0,0],[0,0,0,1]];;
gap> SS:=AffineCrystGroupOnLeft([M1,M2]);;
gap> iso:=IsomorphismPcpGroup(SS);;
gap> S:=Image(iso);;
gap> IsAlmostCrystallographic(S);;
gap> T:=Kernel(NaturalHomomorphismOnHolonomyGroup(S));;
gap> OT := GOuterGroup(S,T);;
gap> P:=ActingGroup(OT);;
gap> R:=ResolutionFiniteGroup(P,3);;
gap> C:=HomToGModule(R,OT);;
gap> CH:=CohomologyModule(C,1);
ZG-module with abelian invariants [ 2 ] and G= Pcp-group with orders [ 2, 2, 3, 2, 2 ]

gap> Elts:=Elements(ActedGroup(CH));
[ g1, id ]
gap> lst := List(Elts{[1..Length(Elts)]},x->CH!.representativeCocycle(x));
[ Standard 1-cocycle 
    , Standard 1-cocycle 
     ]
```
Then, what should I do to extract these dataset?

**Comment by grahamknockillaree** [comment]
An n-cocycle for a group $G$ with coefficients in a $G$-module $A$ is a homomorphism $R_n \rightarrow A$ where $R_\ast$ is a free $\mathbb ZG$-resolution of the trivial module $\mathbb Z$.  So to understand the precise meaning of a cocycle you need to know details of the resolution $R_\ast$.  There is a standard resolution, called the bar resolution, and the cocycles returned by hap correspond to this standard resolution and can thus be thought of as functions $f(g_1,g_2,...,g_n)$ with $g_i\in G$. 

I think you'd need to ask the author/maintainer of your output file Ex4_out what resolution those 1-cocycles correspond to.

Hope this helps.
Graham
