### ISSUE TITLE
Support "convert" from GraphicsMagick?

### ISSUE THREAD

**Issue by orlitzky** [gap-packages/hap#115]
The issue I was debugging over in https://github.com/gap-packages/hap/issues/114 turned out to be the fault of my `convert`. The `convert` utility can actually come from two places. The first, ImageMagick, I guess you already know about. The second is [GraphicsMagick](http://www.graphicsmagick.org/), which is preferable in a lot of ways except that it causes compatibility headaches like this one.

When using ImageMagick, `convert` puts a comment in the header of the text file created by `ReadImageAsPureCubicalComplex`, and each line has an `rgba(...)` field:

```
jumba $ head /tmp/im.txt
# ImageMagick pixel enumeration: 672,507,0,255,rgba
0,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
1,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
2,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
3,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
4,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
5,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
6,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
7,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
8,0: (255,255,255,0)  #FFFFFF00  rgba(255,255,255,0)
```

The `convert` from GraphicsMagick doesn't:

```
gantu $ head /tmp/im.txt
0,0: (255,255,255,255) #FFFFFFFF
1,0: (255,255,255,255) #FFFFFFFF
2,0: (255,255,255,255) #FFFFFFFF
3,0: (255,255,255,255) #FFFFFFFF
4,0: (255,255,255,255) #FFFFFFFF
5,0: (255,255,255,255) #FFFFFFFF
6,0: (255,255,255,255) #FFFFFFFF
7,0: (255,255,255,255) #FFFFFFFF
8,0: (255,255,255,255) #FFFFFFFF
9,0: (255,255,255,255) #FFFFFFFF
```

Why are the alpha values different? Who knows. But maybe it's possible to make `lib/PolyComplexes/prog` parse both formats at once? Otherwise anyone with GraphicsMagick installed is going to get very weird errors.

**Comment by grahamknockillaree** [comment]
The numbers 672 and 507 in the first line of the ImageMagick file are needed to specify the array size of the pure cubical complex. I'm not sure how best to change the perl script so that these two numbers will be created from the GraphicsMagick file.  

The perl script is at ~/hap-1.61/lib/PolyComplexes/prog .

**Comment by orlitzky** [comment]
You can also read the dimensions off the last pixel, e.g.

```
$ cat example.txt
# ImageMagick pixel enumeration: 640,480,0,255,rgb
0,0: (220,110,7)  #DC6E07  rgb(220,110,7)
1,0: (220,110,7)  #DC6E07  rgb(220,110,7)
...
639,479: (220,110,7)  #DC6E07  rgb(220,110,7)
```

That wastes a pass through the file, but perl has been around long enough that it should (famous last words) be able to do that efficiently.

I don't really know perl but I'll see if I can come up with a solution.

**Comment by orlitzky** [comment]
Here's a `prog` that gets the dimensions from the end of the file:

```perl
#!/usr/bin/perl
#
# Convert imagemagick text files to GAP matrices.

($file) = @ARGV;

# Read the last line of the file to obtain the dimensions of the
# matrix. We use "tail" for this because it would be inefficient to
# read all the way to the end of a large file just to obtain the first
# line of our output. It is assumed that "tail" can read backwards
# from the end of file efficiently.
#
# With ImageMagick, the dimensions are also contained in a comment on
# the first line of the file. With GraphicsMagick, however, there is
# no better way to obtain them than to look at the coordinates of the
# last pixel.
my $lastline = do {
  open my $pipe, '-|', "tail", "-n 1", $file
    or die "Can't spawn tail: $!\n";
  <$pipe>;
};

@parts = split /(:|,)/, $lastline;
print("HAPAAA:=[\n  ",$parts[0]+1,",",$parts[2]+1,",");

# Open the file and loop through it, reading each line into an array
# by splitting it on a few different separator characters.
open(INFO, $file);
while(<INFO>) {
  # If this is an ImageMagick (not GraphicsMagick) file,
  # skip the first line with the comment on it.
  next if ( substr($_, 0, 1) eq "#" );

  @parts = split m!(,|:|\(|\))!, $_;

  # Format and print the array. We add one to the indices to convert
  # them from zero-based (imagemagick) to one-based (gap). The
  # separator characters also wind up in the array which is why the
  # indices go up by two each time.
  print(
    "[",
    1+$parts[0],
    ",",
    1+$parts[2],
    ",",
    $parts[6]+$parts[8]+$parts[10],
    "],"
  );
};

# Finally, print the end of the matrix, and close the input file.
print($my,"0];\n");
close(INFO);
```

There's still the problem of the mismatched RGB values, but I think it's highly unlikely that that will turn out to be hap's responsibility to fix.

**Comment by grahamknockillaree** [comment]
Thanks very much for this code.  I've uploaded it. So the next release will include it.

**Comment by orlitzky** [comment]
Thanks! I sent a message to the graphicsmagick mailing list to see if anyone can shed some light on the RGB issue.
