### ISSUE TITLE
Vim: Warning: Input is not from a terminal

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#12]
`gap makedoc.g` now works fine. However, attempt to call release script from ReleaseTools shows a number of `Vim: Warning: Input is not from a terminal` messages. Apparently they are coming from https://github.com/gap-packages/hap/blob/master/lib/TitlePage/vis and https://github.com/gap-packages/hap/blob/master/lib/TitlePage/viscript - any ideas how to fix this?

**Comment by alex-konovalov** [comment]
I've published a release candidate which @grahamknockillaree approves, so apparently these warnings are inconvenient (it takes several minutes to run the script since it pauses after each warning for a couple of seconds) but the script does the job (hopefully). Apparently these scripts tweak GAPDoc-generated pages to look like http://hamilton.nuigalway.ie/Hap/doc/chap0.html, so it will depend on @grahamknockillaree further plans whether we want to fix and keep these scripts or get rid of them and have a more straightforward manual building process, and a website with the top level page looking like https://gap-packages.github.io/hapcryst/ from which you still can navigate to the current `www` but hosted in a dedicated `gh-pages` branch instead of being a subdirectory of the master branch.

There is no need in an immediate answer, but something to think about for one of the next releases.

**Comment by jamesjer** [comment]
Those scripts can be converted to invoke sed instead, which makes them much faster.  Here is what vis would look like:
```
#!/bin/sh
sed -e 's,<Item>,<Br/>,g' \
    -e 's,<Row>,<Br/>,g' \
    -e 's,</Item>,<Br/>,g' \
    -e 's,</Row>,<Br/>,g' \
    -e 's,<Table Align="|l|" >,<Br/>,g' \
    -e 's,</Table>,<Br/>,g' \
    -e 's,<List>,<Br/>,g' \
    -e 's,</List>,<Br/>,g' \
    -e 's,</C>,&<Br/>,g' \
    -e 's,</Index>,&::::::::::::::::::::::::<Br/>,g' \
    -i "$@"
```

And viscript would look like this:
```
#!/bin/sh
sed -e 's,<h3>Contents</h3>,<h2>HAP Functions</h2>,g' \
    -e 's,<p><code,<code,g' \
    -e 's,code></p>,code>,g' \
    -e '16d' \
    -e 's,<body>,&<a href="../www/index.html"><small>HAP home</small></a>,' \
    -e 's,<table,& cellspacing="10",' \
    -i "$@"
```
Some tweaks may be necessary, but that should be close.

**Comment by grahamknockillaree** [comment]
Thanks.  But I have now converted the manual to a version that uses only the standard GAPDoc functions.  So I'll soon upload a version of HAP with vis deleted.

**Comment by grahamknockillaree** [comment]
Fixed this (on my local copy) by removing the vis and viscript files altogether

**Comment by alex-konovalov** [comment]
Ok, thanks. I pulled last commit and it the manual builds for me.
