### ISSUE TITLE
File lib/Kelvin/*.gdold

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#15]
I have noticed a warning in the check for package update logs:

    warning: filename contains '*', which is reserved on Windows: 'pkg/hap-1.22/lib/Kelvin/*.gdold'

This file indeed exists:

https://github.com/gap-packages/hap/blob/master/lib/Kelvin/*.gdold

and should be renamed. `*` in the filename is asking for a trouble.

**Comment by grahamknockillaree** [comment]
Fixed this (on my local copy). Deleted all .gdold files

**Comment by alex-konovalov** [comment]
Closed by 1aea908cf4b0d0f6d3ccede69cc71ea2a5af000d
