### ISSUE TITLE
Fix URLs in PackageInfo

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#16]
For the next release, if it will still stay on @grahamknockillaree's page: change

https://github.com/gap-packages/hap/blob/3d354ad122181b83d5f10519fb84e637e05013f5/PackageInfo.g#L19-L21

because URLs should be http://hamilton.nuigalway.ie/Hap/README.HAP and http://hamilton.nuigalway.ie/Hap/PackageInfo.g

**Comment by grahamknockillaree** [comment]
Fixd this (on my local copy)

**Comment by alex-konovalov** [comment]
Closed by 74cd7316baeaf42882e4da8b05cca6b026d9c154  - thanks @grahamknockillaree
