### ISSUE TITLE
Convert README to markdown

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#17]
Convert https://github.com/gap-packages/hap/blob/master/README.HAP to README.md - it will be better rendered on GitHub and will get badges for Travis and Codecov. Also, do not hardcode release numbers there, to avoid updating it for each release.

**Comment by grahamknockillaree** [comment]
I've half fixed this (on my local copy). I've not used mardown as I'll need to learn it first. But I have included a shel script updateAll.sh which read the version number from file Hap1.23/version and the date from Hap1.23/date and inserts this version and date into all files requiring them.
