### ISSUE TITLE
make new release from GitHub

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#2]
This is the plan for the new release:
- [x] upgrade tests
- [x] set up Travis CI
- [x] set up Codecov 
- [x] set up new webpage
- [x]  publish new release
- [ ] redirect package update system to the new webpage

@grahamknockillaree how would you like to proceed? None of the above modifies mathematical functionality of the package, would you like us to take care of PRs which you will be observing and reviewing?

**Comment by alex-konovalov** [comment]
The default tests of the package are passing:
- for the development version:
  - https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/572936214 
  - https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/jobs/572935901
- for the v1.21 release:
  - https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/572809869
  - https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/573107696 

so I am ticking the 1st box here. Would be a good moment set up Travis CI and Codecov.

**Comment by alex-konovalov** [comment]
Now adding travis and codecov in #7.

**Comment by alex-konovalov** [comment]
@grahamknockillaree for the next step, could please explain how to build the HAP documentation from source?

**Comment by grahamknockillaree** [comment]
The manual is produced using the command

gap> MakeHAPManual();

**Comment by alex-konovalov** [comment]
@grahamknockillaree thanks. I have tried it and got an error, which was caused by the `pdfdoc` directory now being removed from the repository. I have created it locally and it was populated with files in `pdfdoc/newman` subdirectory. What's the meaning of these (morever, there is a `doc/newman` too, with seemingly older versions of these files?

**Comment by grahamknockillaree** [comment]
The pdfdoc/newman director should be present but can be emptied of files.  The function

gap> MakeMAPManual()

populates the directory pdfdoc/newman .   The MakeHAPManual() function is very clumsy and I'm in the process of replacing it with standard GAPDoc functions. But that task will take me some time to complete. So, for the moment, just create an empty pdfdoc/newman directory.

Thanks!

**Comment by grahamknockillaree** [comment]
Hap1.21/lib/TitlePage.makeHapMan.gi usies a GAPDoc and the two shell scripts vis and visscript, and the directory pdfdoc/newman to produce the manual. It is not elegant!

doc/newman is something else, but for the moment the files there are still needed.

As I say, I'm working on a decent manual, and at the same time a decent test file. But this is a lot of work and will progress slowly. So, for HAP 1.22, I'll need the existing clumsy version of the manual.

Thanks.

**Comment by alex-konovalov** [comment]
Thanks, I have submitted PR #11 to add `pdfdoc` directory and a script which we need to use to automate release publishing. 

But is the only difference between these directories are these two files?
$ diff doc/newman/ pdfdoc/newman/
Only in doc/newman/: llaregub
Only in doc/newman/: xmltex

This likely will be improved by the and perhaps you are already working on this. So I am now doing any restructuring now, I suggest to go by small incremental changes, and do 1.22 which has a proper release archive on GitHub, which you can download and publish on the HAP website, and then look at HAP's website at version 1.23.

**Comment by alex-konovalov** [comment]
@grahamknockillaree thanks for merging #13 - I have now published HAP 1.22 archive at https://github.com/gap-packages/hap/releases. Please download it from there, check one more time, and update http://hamilton.nuigalway.ie/Hap/www/ - the package update will then see that http://hamilton.nuigalway.ie/Hap/PackageInfo.g on your webpage has HAP's new version, and will retrieve the package archive (from GitHub).

@fingolfin that's an interesting hybrid approach for publishing release archives on GitHub without updating gh-pages branch, assuming that the webpage exists elsewhere. Could it be a useful option for ReleaseTools?

**Comment by grahamknockillaree** [comment]
Thanks once again.

I've downloaded hap-1.22.tar.gz from GitHub and placed it at http://hamilton.nuigalway.ie/Hap/hap1.22.tar.gz  .  I've placed the corresponding PackageInfo.g at http:/hamilton.nuigalway.ie/Hap/PackageInfo.g .  

Now I'll continue working of the web pages and test functions for HAP.

**Comment by alex-konovalov** [comment]
@grahamknockillaree I think we are pretty close to establish a new HAP website at https://gap-packages.github.io/hap/, which will be completely automatically updated when running a script from ReleaseTools by Max. The https://github.com/gap-packages/hap/blob/master/makedoc.g script is runnable and produces the manual, and that is now works better after your recent reorganisation.

**Comment by grahamknockillaree** [comment]
Great! It was only today that I 'discovered' the build and the codecov buttons.  

So now the test examples cover 41% (whatever that means) and pass the testing process.  Testing is limited to 50 minutes run time, which means I've had to delete the bigger examples.  Also, the build procedure won't allow use of the Linux "convert" command, so I've deleted those examples that use it. Or, rather, I've placed them in tst/testextraextra.  The examples used in the build process can be run from Hap using HapTest(). The complete set of examples can be run using TestHapBook().

**Comment by alex-konovalov** [comment]
Good! For coverage, you can explore https://codecov.io/gh/gap-packages/hap/tree/master/lib (navigate to it from the codecov button) and see what's tested and what not. Click on files and directories to see line by line report.

I think for now this setup is fine - extended tests for the developer, standard for Travis CI and GAP release candidate testing.

**Comment by alex-konovalov** [comment]
This is almost completed - now https://gap-packages.github.io/hap/ serves HAP 1.24!

@grahamknockillaree please set up a redirect from your webpages (probably a number of places point to an old location) and then you may close this issue.

**Comment by alex-konovalov** [comment]
@grahamknockillaree http://hamilton.nuigalway.ie/software.html points to http://hamilton.nuigalway.ie/Hap/www/ - would you be able to change there (and possibly in other places) to point to https://gap-packages.github.io/hap/ ? After that, we will be able to close this issue, considering GitHub migration done, and work on #25.

**Comment by grahamknockillaree** [comment]
The link at  http://hamilton.nuigalway.ie/software.html now points to https://gap-packages.github.io/hap/ . Thanks for spotting this.
