### ISSUE TITLE
Making releases

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#22]
@grahamknockillaree what happened with version 1.23 ? It was never picked up for the redistribution, and is not displayed at https://github.com/gap-packages/hap/releases, but the repository already has number 1.24 in it?

**Comment by grahamknockillaree** [comment]
My mistake.  Hap1.23 was on my web page for a week or so so I just assumed it had been picked up.

**Comment by grahamknockillaree** [comment]
hamilton.nuigalway.ie/Hap/hap1.23.tar.gz

**Comment by alex-konovalov** [comment]
That's why:
```
Package: HAP
# Error (/circa/home/gap-jenkins/pkgadmin/pkgcache/hap/tmp/tmpinfo.g): no pack\
age info bound!
  WARNING (HAP): no success in download of the current info file 
  from http://hamilton.nuigalway.ie/Hap/www/PackageInfo.g
```
I need to fix this, is 1.23 still there? Then I will pick it up.

**Comment by alex-konovalov** [comment]
P.S. This would be still not what we need though - you did not use ReleaseTools to create an archive, so https://github.com/gap-packages/hap/releases does not have a trace of it. We would strongly recommend to use releaseTools, and if you don't know how to run them locally, you can always ask me to run them and publish a release.

**Comment by grahamknockillaree** [comment]
I've placed PackageInfo.g for version 1.23 at http://hamilton.nuigalway.ie/Hap/www/PackageInfo.g .
And the tar file is there too for 1.23 .

**Comment by alex-konovalov** [comment]
Thanks, then I think redirect will work - it will look at http://hamilton.nuigalway.ie/Hap/www/PackageInfo.g and figure out that it points to new URL. 

Except that the link you gave does not work now.

**Comment by grahamknockillaree** [comment]
Apologies.  http://hamilton.nuigalway.ie/Hap/PackageInfo.g

**Comment by alex-konovalov** [comment]
Ok, should now be picked up in couple of hours.

**Comment by grahamknockillaree** [comment]
But its version 1.24 that I'd eventually like as the current version. The v1.23 was release a bit too prematurely!

**Comment by alex-konovalov** [comment]
Never mind, version 1.23 will not be picked up anyway, like it never existed. Here is why: after the switch to keeping releases on GitHub (as explained in #2), `PackageInfo.g` has
```
  ArchiveURL      := Concatenation( ~.SourceRepository.URL,
                                   "/releases/download/v", ~.Version,
                                   "/", LowercaseString(~.PackageName), "-", ~.Version ),
```
So archives of new versions are picked up from GutHub releases. Archives now do not have to be published on your homepage at all.

**Comment by grahamknockillaree** [comment]
There are two issues:

1) testall.g fails on some .tst files, such as those involving crystallographic groups. But Test() works on all .tst files. So somehow this needs to be resolved. The easy way is for me to remove problematic txt files, but I guess that is not the optimal way.

2) I need to learn how to release a version via GitHub.  Is there documentation on this?

**Comment by alex-konovalov** [comment]
For (2) please see https://github.com/gap-system/ReleaseTools

For (1) maybe move them to `tst/testextra`, and then try to fix one by one

**Comment by grahamknockillaree** [comment]
Thanks for (2).  And I'll work on (1).

**Comment by alex-konovalov** [comment]
@grahamknockillaree with HAP 1.24 out, seems this can be closed too.
