### ISSUE TITLE
Commits to gh-pages branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/hap#32]
Hello @grahamknockillaree - could you please let us know what are you doing with gh-pages branch, is that accidental or deliberate?

The idea of this branch is that it is updated as much automatically as possible - in fact for packages fully switched to ReleaseTools it is fully automated, for your package a hybrid procedure described at https://github.com/gap-packages/hap/wiki/HAP-wiki is used, but is still copies files from the master branch and just commits them. What you're trying to do in recent commits to https://github.com/gap-packages/hap/commits/gh-pages looks like placing some additional documentation there, but not to the master branch, so it will not be a part of a package release. Is that intended?

**Comment by grahamknockillaree** [comment]
Apologies!  I didn't realize that the gh-pages get updated automatically.  The master branch has the same files in doc/ as the gh-pages branch. But I'll not upload anything else to the gh-pages.

How long does it take for files in /doc in the master branch to be transferred to /doc in the gh-pages branch?

**Comment by alex-konovalov** [comment]
@grahamknockillaree that' fine - hopefully I spot this before you spent too much time on this. The `gh-pages` should march the latest official release of the package. The transfer to `gh-pages` is a part of publishing a new release, and it's a matter of several minutes, as explained at https://github.com/gap-packages/hap/wiki/HAP-wiki. When there will be a time to publish a new release, I can do that for you - please let me know.

**Comment by grahamknockillaree** [comment]
Hello @alex-konovalov  .  I think that I've managed to update HAP to version 1.26 . But please let me know if I've actually messed things up.

The new version has some functions for congruence subgroups of SL(2,O) with O the ring of integers of certain quadratic number fields.

**Comment by alex-konovalov** [comment]
Thanks @grahamknockillaree - it was picked up:
```
* HAP - new version 1.26 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/hap/releases/download/v1.26/hap-1.26
[ ".tar.gz" ]
  unpacking hap-1.26.tar.gz
  Validation of the info file successful!
  Package HAP 1.26 from 04/05/2020 has dependencies:
  * NeededOtherPackages [ [ "polycyclic", ">=1.1" ], [ "crystcat", ">=1.1" ], 
  [ "fga", ">=1.1" ], [ "aclib", ">=1.1" ], [ "nq", ">=1.1" ] ]
  * GAP >= 4.5.6
  * SuggestedOtherPackages [ [ "gapdoc", ">=0.0" ], [ "nql", ">=0.0" ], 
  [ "homology", ">=0.0" ], [ "edim", ">=1.2.2" ], 
  [ "singular", ">=06.07.23" ], [ "congruence", ">=0,0" ], 
  [ "HAPcryst", ">=0.0.0" ], [ "xmod", ">0.0" ] ]
  * ExternalConditions 
[ 
  [ "Some optional functions require Polymake software", 
      "http://polymake.org/doku.php" ], 
  [ "Some optional functions require Graphviz software", 
      "http://www.graphviz.org/" ], 
  [ "One optional function requires the Simplicial Homology GAP package", 
      "http://www.cis.udel.edu/~dumas" ] ]
```
One of the warnings in the log:
```
pkg/hap-1.26/lib/Perturbations/Gcomplexes/GL3O-5HAP: up to 37 MB of RAM may be required to manage this file
```
- this is a new file, it seems, is it needed? One can consider gzipping it, if it's not often modified.

**Comment by grahamknockillaree** [comment]
Thank @alex-konovalov  for spotting this.  No file should be that size.  I'll look into it.

**Comment by grahamknockillaree** [comment]
Hi @alex-konovalov,  many of the files in pkg/hap-1.26/lib/Perturbations/Gcomplexes/ are actually quite large. So I'll now work on gzipping them all.

**Comment by alex-konovalov** [comment]
@grahamknockillaree thaanks, that will be useful
