### ISSUE TITLE
older version of HAP manual

### ISSUE THREAD

**Issue by grahamknockillaree** [gap-packages/hap#33]
Hi @alex-konovalov ,   the following link should probably be removed from the web.

https://www.gap-system.org/Manuals/pkg/Hap1.9/www/

**Comment by alex-konovalov** [comment]
Thanks @grahamknockillaree - indeed, the current setup does not delete old versions of packages, and some discussion of that is at https://github.com/gap-system/GapWWW/issues/105 and https://github.com/gap-system/ReleaseTools/issues/68. It would be useful to address this problem in a consistent and universal way...
