### ISSUE TITLE
Failing tests because of missing dependencies

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#36]
I am currently running the tests for HAP. Doing this I have found that several tests depend on HAPCryst. Installing this did however not remove all failures. There are now several tests that seemingly fail because HAPPrime is missing. This is not an official GAP package, not even suggested by HAP and seems unmaintained for about a decade. 

It seems somewhat tedious to resolve all these test failures. Tests that depend on on other packages should not run or report the dependency as a cause of their failure.

**Comment by narc-Ontakac2** [comment]
Actually HAPPrime is the main issue here. All other tests are running by now.

**Comment by grahamknockillaree** [comment]
These tests require the Singular system https://www.singular.uni-kl.de/ to be loaded.

The HAPprime package is no longer used. Relevant code from this package as been modified and stored as part of HAP.
