### ISSUE TITLE
Minor Cleanup

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#37]
While packaging GAP several minor issues came up, mostly found by lintian:
The following files are garbage and should be removed.
www/SideLinks/About/crystal.fig.bak
www/SideLinks/About/7dimBieberback.gOLD
www/SideLinks/About/aboutCubical.htmlOLD
www/SideLinks/About/aboutCrossedMods

In
doc/newHapMan.xml
there is broken XML:
<#Include SYSTEM newFunctionsKnotsQuandles.xml">

lib/PolyComplexes/oldprog
is a copy of
lib/PolyComplexes/prog
and should be removed. prog itself has a perl path containing local, which should be changed to one that will work on most systems (/usr/bin/perl).

A patch doing all this 
[cleanup_garbage.txt](https://github.com/gap-packages/hap/files/5606062/cleanup_garbage.txt)
is attached.

**Comment by alex-konovalov** [comment]
Curious why #41 fixing this #37 and #38 was closed but this issue has been reopened. Accidentally perhaps?

**Comment by alex-konovalov** [comment]
Curious why #41 fixing this #37 and #38 was closed but this issue has been reopened. Accidentally perhaps?

**Comment by grahamknockillaree** [comment]
I think this was re-opened by mistake.
