### ISSUE TITLE
Missing "Suggests" for polymaking

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#39]
HAP uses the polymaking package directly (in lib/Polymake/convexCWspace.gi). Therefore this should be listed as a suggested package so that it is autoloaded if present.
[info.polymaking.txt](https://github.com/gap-packages/hap/files/5647987/info.polymaking.txt)

**Comment by grahamknockillaree** [comment]
I added Polymaking as a suggested package.
