### ISSUE TITLE
Incompatible to Polymake 4.1

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#40]
The polymake compatibility issue from gap polymaking affects HAP too. Unfortunately examples 1.1.1 and 1.2.1 are failing because of this.

**Comment by narc-Ontakac2** [comment]
If my fix for polymaking is accepted it might make sense to fix this by using polymaking from HAP for all calls to polymake. Any opinions on this?

**Comment by jamesjer** [comment]
It looks like a fix for this was merged for the 1.28 release, but I am still encountering 2 issues when building for Fedora:
1. The callPolymake function in lib/Polymake/fix.gi still calls polymake the old way; i.e., it does not use the wrapper that POLYMAKE_PATH points to.
2. The output when FEASIBLE is requested is one of the strings "false" or "true".  The code in lib/Polymake/aspherical.gi expects an integer output, 0 or 1.  Converting "true" to Int on line 192 fails, causing HAP to report "Test inconclusive." for all inputs.

I am using this patch as a workaround for now: https://src.fedoraproject.org/rpms/gap-pkg-hap/blob/master/f/gap-pkg-hap-polymake4.patch

**Comment by narc-Ontakac2** [comment]
I did not know about this fix. I am using  1.25 for debian packaging, which I think is the official stable release.

I have a patch for that in "works for me" quality, which moves all polymake calls to the polymaking package. It removes some redundant code, but is much more invasive.

**Comment by narc-Ontakac2** [comment]
I can confirm that the patch is working. I am now on HAP 1.29. After applying the patch and excluding the tests that require happrime or laguna all tests succeed.

**Comment by alex-konovalov** [comment]
@narc-Ontakac2 BTW, why do you need to remove [LAGUNA](https://gap-packages.github.io/laguna/) tests - this package is redistributed with GAP?

**Comment by narc-Ontakac2** [comment]
Because I am a bit lazy. Only 2 tests require LAGUNA, and it is not among the packages I am packaging for debian.

**Comment by grahamknockillaree** [comment]
HAP now passes all tests with Polymake version 3.2 or 4.3 provided the updated Polymaking V0.8.4 is used.
