### ISSUE TITLE
Possible bug in HAP?

### ISSUE THREAD

**Issue by jmichel7** [gap-packages/hap#42]
Hello,
Ivan  Marin and  me have  been trying  to answer  a question of Jean-Pierre
Serre  using HAP.  Doing  this, we stumbled  on what might  be a bug in HAP.
Serre  wants to know if  the Coxeter group B_6  has a non-trivial action on
H^3(D_6,Z/2).  His  idea  is  to  compare  the restrictions from D_6 to the
(conjugate  in  B_6  but  not  in  D_6)  parabolic  subgroups of type A_1^3
generated by the reflections (1,4,6) and (2,4,6).

Following the example in

https://gap-packages.github.io/hap/www/SideLinks/About/aboutFunctorial.html

We tried the following (for the first of these A_1^3 subgroups called here C1)

```
LoadPackage("HAP");
DD6:=[[1,[3,3]],[2,[3,3]],[3,[1,3],[2,3],[4,3]],[4,[3,3],[5,3]],
      [5,[4,3],[6,3]],[6,[5,3]]];
R:=ResolutionCoxeterGroup(DD6,4);
D6:=R.!group;
C1:=Group([D6.1,D6.4,D6.6]);
RC1:=ResolutionFiniteGroup(C1,4);
fC1:=GroupHomomorphismByFunction(C1,D6,x->x);
fC1map:=EquivariantChainMap(R,RC1,fC);
mapfC1Z:=TensorWithIntegers(fC1map);
HmapfC1Z:=Homology(mapfC1Z,2);  
```

But the last command given an error (method not found).
Is this expected?

**Comment by narc-Ontakac2** [comment]
The above is not working because of typos. I am adding what probably was intended including the full error message.
```
gap> DD6:=[[1,[3,3]],[2,[3,3]],[3,[1,3],[2,3],[4,3]],[4,[3,3],[5,3]],
      [5,[4,3],[6,3]],[6,[5,3]]];
[ [ 1, [ 3, 3 ] ], [ 2, [ 3, 3 ] ], [ 3, [ 1, 3 ], [ 2, 3 ], [ 4, 3 ] ], 
  [ 4, [ 3, 3 ], [ 5, 3 ] ], [ 5, [ 4, 3 ], [ 6, 3 ] ], [ 6, [ 5, 3 ] ] ]
gap> R:=ResolutionCoxeterGroup(DD6,4);
Resolution of length 4 in characteristic 
0 for <permutation group of size 23040 with 6 generators> . 
No contracting homotopy available. 

gap> D6:=R!.group;
<permutation group of size 23040 with 6 generators>
gap> C1:=Group([D6.1,D6.4,D6.6]);
<permutation group with 3 generators>
gap> RC1:=ResolutionFiniteGroup(C1,4);
Resolution of length 4 in characteristic 
0 for <permutation group of size 8 with 3 generators> . 

gap> fC1:=GroupHomomorphismByFunction(C1,D6,x->x);
MappingByFunction( <permutation group with 3 generators>, <permutation group o\
f size 23040 with 6 generators>, function( x ) ... end )

gap> fC1map:=EquivariantChainMap(R,RC1,fC1);
Equivariant Chain Map between resolutions of length 4 . 

gap> mapfC1Z:=TensorWithIntegers(fC1map);
Chain Map between complexes of length 4 . 

gap> HmapfC1Z:=Homology(mapfC1Z,2);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `[]' on 2 arguments
The 2nd argument is 'fail' which might point to an earlier problem
 at /usr/share/gap/lib/methsel2.g:249 called from
return Multmat[i][j]
 ; at /usr/share/gap/pkg/HAP/lib/Functors/equiChainMap.gi:87 called from
Mult( GhomQ( x[2] ), b[2] 
 ) at /usr/share/gap/pkg/HAP/lib/Functors/equiChainMap.gi:125 called from
func( list[i] ) at /usr/share/gap/lib/list.gi:2049 called from
Apply( y, function ( b )
      return [ b[1], Mult( GhomQ( x[2] ), b[2] ) ];
  end ); at /usr/share/gap/pkg/HAP/lib/Functors/equiChainMap.gi:125 called from
mapgens( x[1], m ) at /usr/share/gap/pkg/HAP/lib/Functors/equiChainMap.gi:183 called from
...  at *stdin*:11
type 'quit;' to quit to outer loop

```
Unfortunately I do not have an answer.

**Comment by grahamknockillaree** [comment]
Hi,

I only got to see this question now. In order to construct a chain map of resolutions RC1-->RG we need to have a contracting homotopy implemented on the resolution RG. The resolution RG=ResolutionCoxeterGroup(DD6,4) has no contracting homotopy implemented at present. I got as far as writing down an algorithm/formula for a contracting homotopy for Coxeter groups (the fun part) but never got around to implementing it (the less fun part).

However, your Coxeter group D6 is finite and not too large, so we could treat it as a generic finite group.  The following commands compute the required homology homomorphismHmapfC1Z.

gap> DD6:=[[1,[3,3]],[2,[3,3]],[3,[1,3],[2,3],[4,3]],[4,[3,3],[5,3]],
>       [5,[4,3],[6,3]],[6,[5,3]]];;
gap> F:=CoxeterDiagramFpCoxeterGroup(DD6);;
gap> D6:=Image(IsomorphismPermGroup(F[1]/F[2]));;
gap> R:=ResolutionSubnormalSeries(CompositionSeries(D6),4);;
gap> C1:=Group([D6.1,D6.4,D6.6]);;
gap> RC1:=ResolutionFiniteGroup(C1,4);;
gap> fC1:=GroupHomomorphismByFunction(C1,D6,x->x);;
gap> fC1map:=EquivariantChainMap(RC1,R,fC1);;
gap> mapfC1Z:=TensorWithIntegers(fC1map);;
gap> HmapfC1Z:=Homology(mapfC1Z,2);
[ g1, g2, g3 ] -> [ g1, g1, g1 ]

Hope this answers the question.

Graham

**Comment by grahamknockillaree** [comment]
@jmichel7   I forgot to include your name in my comment. I'll do so now so that you get notification of the comment.

**Comment by jmichel7** [comment]
On Fri, Apr 09, 2021 at 11:30:09AM -0700, grahamknockillaree wrote:
> I only got to see this question now. In order to construct a chain map of resolutions RC1-->RG we need to have a contracting homotopy implemented on the resolution RG. The resolution RG=ResolutionCoxeterGroup(DD6,4) has no contracting homotopy implemented at present. I got as far as writing down an algorithm/formula for a contracting homotopy for Coxeter groups (the fun part) but never got around to implementing it (the less fun part).
> 
> However, your Coxeter group D6 is finite and not too large, so we could treat it as a generic finite group.  The following commands compute the required homology homomorphismHmapfC1Z.
> 
> gap> DD6:=[[1,[3,3]],[2,[3,3]],[3,[1,3],[2,3],[4,3]],[4,[3,3],[5,3]],
> >       [5,[4,3],[6,3]],[6,[5,3]]];;
> gap> F:=CoxeterDiagramFpCoxeterGroup(DD6);;
> gap> D6:=Image(IsomorphismPermGroup(F[1]/F[2]));;
> gap> R:=ResolutionSubnormalSeries(CompositionSeries(D6),4);;
> gap> C1:=Group([D6.1,D6.4,D6.6]);;
> gap> RC1:=ResolutionFiniteGroup(C1,4);;
> gap> fC1:=GroupHomomorphismByFunction(C1,D6,x->x);;
> gap> fC1map:=EquivariantChainMap(RC1,R,fC1);;
> gap> mapfC1Z:=TensorWithIntegers(fC1map);;
> gap> HmapfC1Z:=Homology(mapfC1Z,2);
> [ g1, g2, g3 ] -> [ g1, g1, g1 ]
> 
> Hope this answers the question.

Thanks a lot! This is very useful...
------------------------------------------------------------------------------
Jean MICHEL, Groupes et representations, IMJ-PRG UMR7586 tel.(33)157279144
Bureau 639 Bat. Sophie Germain Case 7012 - 75205 PARIS Cedex 13
