### ISSUE TITLE
Release Tools

### ISSUE THREAD

**Issue by grahamknockillaree** [gap-packages/hap#50]
@fingolfin @alex-konovalov   I've successfully updated the page https://gap-packages.github.io/hap/ except for one major error: the file https://github.com/gap-packages/hap/releases/download/v1.30/hap-1.30.tar.gz has not been created. The following is how I am (incorrectly?) using the Release Tools. Any tips would be much appreciated.

~/hap$ ../ReleaseTools/release-gap-package --token ghp_i've_redacted_the_actual_token
Extracting information from PackageInfo.g...
Package HAP 1.30
Building GAP package documentation (using makedoc.g)
Using archive basename hap-1.30
Using GitHub repository gap-packages/hap
Using GitHub username gap-packages
Using branch master
Creating git tag v1.30

Exporting repository content for tag 'v1.30'
Removing unnecessary files
rm: cannot remove '.github': Is a directory
graham@whitehead:~/hap$

**Comment by fingolfin** [comment]
You are using an older version of the tool; update to the latest and try again?

**Comment by grahamknockillaree** [comment]
Yippee -- it worked.  Thanks. :)
