### ISSUE TITLE
The movement of the tutorial directory is incomplete

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#54]
There are as far as I can see several things missing:

1. The directory doc/tutorial still exists,
2. the tutorial directory does not have css and js files because makedoc.g has not been adapted and
3. the directory tutorial is not in the ArchiveURLSubset in PackageInfo.g.

**Comment by grahamknockillaree** [comment]
I've made these adjustments just now.

I'm not sure if it is in anyway related, but  the GAP release tool now crashes with the error

Error, unknown option relativePath at /usr/share/gap-4.11.1/pkg/nq-2.5.4/gap/nq.gi:143 called from


I'm not sure if this is related to HAP or not.

**Comment by grahamknockillaree** [comment]
II've made these three changes and uploaded HAP v1.33.   Thanks.

**Comment by narc-Ontakac2** [comment]
On 30.06.21 17:29, grahamknockillaree wrote:
> I'm not sure if it is in anyway related, but the GAP release tool now
> crashes with the error
>
> Error, unknown option relativePath at
> /usr/share/gap-4.11.1/pkg/nq-2.5.4/gap/nq.gi:143 called from
>
This is quite sure not HAP related. The documentation build seems to be
using the relativePath option (I have a patch for my debian build that
does the same) and it seems this is no longer supported by GAP.

@Max Horn: Is this something for you?

Sincerely,

Joachim

> -- 

Papier ist gebundenes CO2. Bitte drucken Sie diese EMail aus und archivieren Sie sie.

**Comment by grahamknockillaree** [comment]
Hi,

This was in fact HAP related.  I had accidentally left some test lines in hap/lib/Manifolds/simplicialcup.gi which called the called the Nq package. I've now deleted these lines and the release tools work fine.

Sorry for the unnecessary confusion. :)

Graham


School of Mathematics, Statistics & Applied Mathematics
National University of Ireland, Galway
tel: 091 493011



________________________________
