### ISSUE TITLE
Broken WWWHome link for Graham

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/hap#64]
In `PackageInfo.g` the `WWWHome` field for @grahamknockillaree is set to http://hamilton.nuigalway.ie but this URL returns an error for me.

**Comment by grahamknockillaree** [comment]
I'll change the address to https://github.com/gap-packages/hap

**Comment by grahamknockillaree** [comment]
Changed the address to my official university address. Due to tightened security after a Russian cyber-attack on the University my personal pages are no longer accessible. :(
