### ISSUE TITLE
hap 1.39 release missing

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/hap#67]
The website https://gap-packages.github.io/hap/ lists 1.39 as latest release, but the download link is broken. Indeed, no 1.39 releases can be found at https://github.com/gap-packages/hap/releases and hence also no .tar.gz

The *tag* is there at https://github.com/gap-packages/hap/tags but it's not a release.

Perhaps a problem running the `release-gap-package` script? I've made a bunch of changes to it recently, so you may want to re-download it, and then try again to release 1.39, possibly with the `--force` option to force it to re-release

**Comment by grahamknockillaree** [comment]
Thanks. I followed your suggestions. The 1.39 release is now available.

**Comment by fingolfin** [comment]
Confirmed, it works now. Thanks
