### ISSUE TITLE
HAP 1.40 fails to load with only required packages

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/hap#68]
The package update for HAP 1.40 fails to load when instructing GAP to only load "needed" packages, as declared in the `PackageInfo.g`:
```
#I  HAP: start reading file 'init.g'
#I  HAP warning: Set NEATO_PATH manually if needed.
#I  HAP warning: Set DOT_PATH manually if needed.
#I  HAP warning: Set ASY_PATH manually if needed.
#I  HAP: finish reading file 'init.g'
#I  HAP: start reading file 'read.g'
Error, Variable: 'IsPolymakeObject' must have a value
```
My guess is that either `polymaking` must be move to the "needed" package list, or the code must be fixed to access `IsPolymakeObject` only when `polymaking` is loaded.

**Comment by grahamknockillaree** [comment]
Thanks for pointing this out.

I'm keen to keep to a minimum the packages needed to allow HAP to load.  So I'll insert the following in HAP and release a newer version.

if not LoadPackage("polymaking")  then DeclareCategory("IsPolymakeObject",IsObject); fi;

**Comment by grahamknockillaree** [comment]
I guess the following is a better solution.

if not IsPackageMarkedForLoading("polymaking",0.8.3) then DeclareCategory("IsPolymakeObject",IsObject); fi;

**Comment by fingolfin** [comment]
That's problematic: if you do that, then loading polymake later on won't be possibly anymore, as it will try to declare `IsPolymakeObject` which now already exists

**Comment by fingolfin** [comment]
As I see it, you only use `IsPolymakeObject` in one single line in all of hap: for a `Display` method for `IsPolymakeObject`. 

You could simply wrap that code in a check. I.e.:
```
if IsPackageMarkedForLoading("polymaking",0.8.3) then

InstallOtherMethod(Display,
"method for displaying convex hulls of sets of points",
[IsPolymakeObject],
...

end);
fi;

**Comment by grahamknockillaree** [comment]
I've inserted a version of the above IsPackageAvailableForLoading command into the read.g file.  I think this fixes the problem so I'll close #68.  Thanks again.

**Comment by narc-Ontakac2** [comment]
This has slightly changed with 1.41 :

gap> LoadPackage("HAP");
...
Syntax warning: Unbound global variable in /usr/share/gap/pkg/HAP/lib/Polymake\
/orbitPoly.gi:126
Dim:=Length(Polymake(F,"F_VECTOR"));
            ^^^^^^^^
Syntax warning: Unbound global variable in /usr/share/gap/pkg/HAP/lib/Polymake\
/orbitPoly.gi:127
Points:=Polymake(F,"VERTICES");
        ^^^^^^^^
Loading HAP 1.41 ...
true

**Comment by fingolfin** [comment]
I've submitted PR #70 to deal with those syntax warnings

**Comment by grahamknockillaree** [comment]
I've replace the read.g file with the modified one produced by @fingolfin
