### ISSUE TITLE
`LoadPackage("HAPcocyclic");` doesn't work.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#74]
According to the description [here](https://gap-packages.github.io/hap/www/SideLinks/About/aboutGouter.html), I tried the following but failed:

```gap
gap> LoadPackage("HAPcocyclic");
#I  hapcocyclic package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
fail
```

But I've all the needed files at the following location:

```bash
werner@X10DAi-00:~$ ls ~/Public/repo/github.com/gap-system/gap.git/pkg/hap/lib/HapCocyclic/
gap  init.g  PackageInfo.g  read.g  README  readme_Aug2014  tst
```
Any hints for this problem?

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
The following command is no longer necessary 
gap> LoadPackage("HAPcocyclic");;
and I should update the old html HAP manual. In general, it is better to consult the [new manual](https://gap-packages.github.io/hap/tutorial/chap6_mj.html#X8333413B838D787D).

The HAPcocyclic functions have been moved to HAP and load when HAP is loaded.

**Comment by hongyi-zhao** [comment]
Whether the problem discussed [here](https://github.com/gap-packages/hap/issues/72#issuecomment-1179006560) must be addressed based on the functionality provided by this module?
