### ISSUE TITLE
Check/confirm/verify the isomorphism between two space groups with the help of HAP package.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#75]
According to the explanation [here](http://aflowlib.org/prototype-encyclopedia/enantiomorph_info.html), space groups $P3_1$​ (#144) and $P3_2$​ (#145) are a pair of enantiomorphic space groups ([Online Dictionary of Crystallography](http://dictionary.iucr.org/Main_Page), [ITC-A](http://it.iucr.org/Ab/)), so they are isomorphic. 

I try to check/confirm/verify the isomorphism between them as follows but failed:
```gap
gap> g1:=SpaceGroupPcpGroup(3,144);
Pcp-group with orders [ 3, 2, 0, 0, 0 ]
gap> g2:=SpaceGroupPcpGroup(3,145);
Pcp-group with orders [ 2, 3, 0, 0, 0 ]
gap> IsomorphismGroups(g1,g2);
Error, cannot test isomorphism of infinite groups at /home/werner/Public/repo/github.com/gap-system/gap.git/lib/morpheus.gi:2835 called from
<function "IsomorphismGroups">( <arguments> )
 called from read-eval loop at *stdin*:4
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```
So, I want to know whether this can be done with the help of HAP package.

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
The groups are not isomorphic because:

gap> GroupHomology(g1,1);
[ 2, 6 ]
gap> GroupHomology(g2,1);
[ 2, 2 ]

**Comment by hongyi-zhao** [comment]
Sorry, I intended to write it in the form below, but due to my carelessness at the time I wrote it in a form I did not want:
```gap
gap> g1:=Image(IsomorphismPcpGroup(SpaceGroupBBNWZ(3,144)));
Pcp-group with orders [ 3, 0, 0, 0 ]
gap> g2:=Image(IsomorphismPcpGroup(SpaceGroupIT(3,145)));
Pcp-group with orders [ 3, 0, 0, 0 ]
gap> GroupHomology(g1,1);
[ 3, 0 ]
gap> GroupHomology(g2,1);
[ 3, 0 ]
```
Do you mean that the `GroupHomology` command can verify isomorphism in this way?

Is so, the problem disuccessed [here](https://github.com/gap-packages/hap/issues/72#issuecomment-1173403369) and [here](https://github.com/gap-packages/hap/issues/72#issuecomment-1174789623) can be solved as follows:

```gap
gap> pcpBieb:=Filtered([1..219], x -> IsAlmostBieberbachGroup(SpaceGroupPcpGroup(3,x)));
[ 1, 4, 7, 9, 19, 33, 34, 76, 142, 165 ]
gap> sgBieb:=Filtered([1..230], x-> IsAlmostBieberbachGroup(Image(IsomorphismPcpGroup(SpaceGroupBBNWZ(3,x)))));
[ 1, 4, 7, 9, 19, 29, 33, 76, 78, 144, 145, 169, 170 ]

gap> for i in pcpBieb do
>    ghpcp:=GroupHomology(SpaceGroupPcpGroup(3,i),1);
>    for j in sgBieb do
>      ghsg:=GroupHomology(Image(IsomorphismPcpGroup(SpaceGroupBBNWZ(3,j))),1);
>      if ghsg = ghpcp then
>        Print("SpaceGroupPcpGroup (3, ", i,") is isomorphic to SpaceGroupBBNWZ (3, ", j,")\n");
>      fi;
>    od;
> od;
SpaceGroupPcpGroup (3, 1) is isomorphic to SpaceGroupBBNWZ (3, 1)
SpaceGroupPcpGroup (3, 4) is isomorphic to SpaceGroupBBNWZ (3, 4)
SpaceGroupPcpGroup (3, 4) is isomorphic to SpaceGroupBBNWZ (3, 29)
SpaceGroupPcpGroup (3, 7) is isomorphic to SpaceGroupBBNWZ (3, 7)
SpaceGroupPcpGroup (3, 9) is isomorphic to SpaceGroupBBNWZ (3, 9)
SpaceGroupPcpGroup (3, 19) is isomorphic to SpaceGroupBBNWZ (3, 19)
SpaceGroupPcpGroup (3, 33) is isomorphic to SpaceGroupBBNWZ (3, 4)
SpaceGroupPcpGroup (3, 33) is isomorphic to SpaceGroupBBNWZ (3, 29)
SpaceGroupPcpGroup (3, 34) is isomorphic to SpaceGroupBBNWZ (3, 33)
SpaceGroupPcpGroup (3, 76) is isomorphic to SpaceGroupBBNWZ (3, 76)
SpaceGroupPcpGroup (3, 76) is isomorphic to SpaceGroupBBNWZ (3, 78)
SpaceGroupPcpGroup (3, 142) is isomorphic to SpaceGroupBBNWZ (3, 144)
SpaceGroupPcpGroup (3, 142) is isomorphic to SpaceGroupBBNWZ (3, 145)
SpaceGroupPcpGroup (3, 165) is isomorphic to SpaceGroupBBNWZ (3, 169)
SpaceGroupPcpGroup (3, 165) is isomorphic to SpaceGroupBBNWZ (3, 170)
```

And also the isomorphism problem between a self created crystallographic space group from scratch and the corresponding ones provided by [cryst](https://www.gap-system.org/Packages/cryst.html)/[crystcat](https://www.gap-system.org/Packages/crystcat.html) packages can be verified as follows:
```gap
gap> GenSG227Left:=[[[0, 1, 0, 0], [1, 0, 0, 0], [-1, -1, -1, 0], [0, 0, 0, 1]],
> [[-1, -1, -1, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [1, 1, 1, 1/4], [0, 0, 0, 1]],
> [[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [0, 0, -1, 1/4], [0, 0, 0, 1]]];;
gap> 
gap> SG227Left:=AffineCrystGroupOnLeft(GenSG227Left);
<matrix group with 5 generators>
gap> GroupHomology(Image(IsomorphismPcpGroup(SG227Left)),1);
[ 2, 2 ]
gap> GroupHomology(SpaceGroupOnLeftBBNWZ(3,227),1);
[ 2, 2 ]
gap> GroupHomology(Image(IsomorphismPcpGroup(SpaceGroupIT(3,227))),1);
[ 2, 2 ]
```

**Comment by hongyi-zhao** [comment]
It seems that all my above statements on the accurate/explicit isomorphism determination between two different space groups are wrong. And for this problem, Eick, Bettina <b.eick@tu-braunschweig.de> told me the following point of view: 


> Dear Hongyi Zhao,
>
> in general, testing isomorphism of infinite groups is algorithmically a difficult problem.
> 
> I think that in the case of 3-dimensional space groups testing isomorphism is a decidable problem, but I am not aware of an implementation. 
> 
> Best wishes,
> Bettina 
 
In addition, I just found the following paper which may be related to the problem discussed here:

https://www.sciencedirect.com/science/article/abs/pii/S0021869320303756#!

Distinguishing crystallographic groups by their finite quotients

**Comment by grahamknockillaree** [comment]
Homology is an **invariant** so can only be used to show that two space groups are **not** isomorphic.  The following commands are enough for you to decided isomorphism between 3-dimensional Bieberbach groups.

gap> pcpBieb:=Filtered([1..219], x -> IsAlmostBieberbachGroup(SpaceGroupPcpGroup(3,x)));;
gap> inv:=function(k);
> return List([1..3],i->GroupHomology(SpaceGroup(3,k),i));
> end;;
gap> C:=Classify(pcpBieb,inv);
[ [ 1 ], [ 4 ], [ 7 ], [ 9 ], [ 19 ], [ 33 ], [ 34 ], [ 76 ], [ 142 ], 
  [ 165 ] ]
gap> #So all 10 Bieberbach groups have distinct isomorphism types.

gap> sgBieb:=Filtered([1..230], x-> IsAlmostBieberbachGroup(Image(IsomorphismPcpGroup(SpaceGroupBBNWZ(3,x)))));;
gap> inv2:=function(k);
> return List([1..3],i->GroupHomology(SpaceGroupBBNWZ(3,k),i));
> end;;
gap> C:=Classify(sgBieb,inv2);
[ [ 1 ], [ 4 ], [ 7 ], [ 9 ], [ 19 ], [ 29 ], [ 33 ], [ 76, 78 ], 
  [ 144, 145 ], [ 169, 170 ] ]
gap> #So groups 76 and 78 are isomorphic, as are 144 and 145, and as are 169 and 170.

**Comment by hongyi-zhao** [comment]
Mine is as follows:
```gap
gap> pcpBieb:=Filtered([1..219], x -> IsAlmostBieberbachGroup(SpaceGroupPcpGroup(3,x)));;
gap> inv:=function(k);
>  return List([1..3], i -> GroupHomology(SpaceGroup(3,k),i));
> end;;
gap> C:=Classify(pcpBieb,inv); time;
[ [ 1 ], [ 4 ], [ 7 ], [ 9 ], [ 19 ], [ 33 ], [ 34 ], [ 76 ], [ 142 ], [ 165 ] ]
4897
```

**Comment by grahamknockillaree** [comment]
The following commands, which do not use any HAP functions, show that the abelian invariants of finite index subroups of index less than or equal to 8 suffice to distinguish between the isomorphism types of all 219 space groups.

```gap
gap> inv:=function(k,d)
> local L,G;
> G:=SpaceGroup(3,k);;
> G:=Image(IsomorphismFpGroup(G));;
> L:=LowIndexSubgroupsFpGroup(G,d);;
> L:=List(L,AbelianInvariants);;
> L:=SortedList(L);;
> return L;;
> end;;
gap> C:=Classify([1..219],k->inv(k,5));;
gap> Length(C);
199
gap> C:=RefineClassification(C,k->inv(k,6));;
gap> Length(C);
213
gap> C:=RefineClassification(C,k->inv(k,7));;
gap> Length(C);
213
gap> C:=RefineClassification(C,k->inv(k,8));;
gap> Length(C);
219
```

**Comment by hongyi-zhao** [comment]
Wonderful trick. But this still can't distinguish the 11 pairs of [enantiomorphic](http://aflowlib.org/prototype-encyclopedia/enantiomorph_info.html) (or [chiral](https://dictionary.iucr.org/Chiral_space_group)) space groups, as shown below:

```gap
gap> inv:=function(k,d)
>  local L,G;
>  # G:=SpaceGroup(3,k);; # [1..219]
>  G:=SpaceGroupBBNWZ(3,k);; # [1..230]
>  G:=Image(IsomorphismFpGroup(G));;
>  L:=LowIndexSubgroupsFpGroup(G,d);;
>  L:=List(L,AbelianInvariants);;
>  L:=SortedList(L);;
>  return L;;
> end;;

gap> C:=Classify([1..230],k->inv(k,5));;
gap> C:=RefineClassification(C,k->inv(k,8));;
gap> Length(C);
219
gap> Filtered(C,x->Size(x)>1);
[ [ 76, 78 ], [ 91, 95 ], [ 92, 96 ], [ 144, 145 ], [ 151, 153 ], [ 152, 154 ], [ 180, 181 ], [ 178, 179 ], [ 169, 170 ], [ 171, 172 ], [ 212, 213 ] ]
```
Another question: How to use one command to achieve the purpose of the following commands?
```gap
gap> C:=Classify([1..230],k->inv(k,5));;
gap> C:=RefineClassification(C,k->inv(k,8));;
```
Side remark: This method has good scalability, that is, it can also be used for space groups higher than 3 dimensions.

**Comment by hongyi-zhao** [comment]
https://github.com/gap-packages/hap/issues/75#issuecomment-1180190400

> Based on your above trick, I figured out the following method to solve the isomorphism problem between a self created crystallographic space group from scratch and the corresponding ones provided by [cryst](https://www.gap-system.org/Packages/cryst.html) or [crystcat](https://www.gap-system.org/Packages/crystcat.html) packages can be verified as follows:
> 
> ```gap
> gap> GenSG227Left:=[[[0, 1, 0, 0], [1, 0, 0, 0], [-1, -1, -1, 0], [0, 0, 0, 1]],
> > [[-1, -1, -1, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> > [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [1, 1, 1, 1/4], [0, 0, 0, 1]],
> > [[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> > [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [0, 0, -1, 1/4], [0, 0, 0, 1]]];;
> gap> SG227Left:=AffineCrystGroupOnLeft(GenSG227Left);;
> gap> #Verify the SG227Left and SpaceGroupBBNWZ(3,227) are isomorphic
> gap> gh1:=List([1..3],i->GroupHomology(Image(IsomorphismPcpGroup(SG227Left)),i));
> [ [ 2, 2 ], [ 2, 2, 2 ], [ 2, 2, 2, 2, 2, 12 ] ]
> gap> gh2:=List([1..3], i-> GroupHomology(SpaceGroupBBNWZ(3,227), i));
> [ [ 2, 2 ], [ 2, 2, 2 ], [ 2, 2, 2, 2, 2, 12 ] ]
> gap> gh1=gh2;
> true
> ```

The above method should be amended as follows:
```gap
gap> inv2:=function(S,d)
>  local L,G;
>  # G:=SpaceGroup(3,k);; # [1..219]
> #  G:=SpaceGroupBBNWZ(3,k);; # [1..230]
>  G:=Image(IsomorphismFpGroup(S));;
>  L:=LowIndexSubgroupsFpGroup(G,d);;
>  L:=List(L,AbelianInvariants);;
>  L:=SortedList(L);;
>  return L;;
> end;;
gap> GenSG227Left:=[[[0, 1, 0, 0], [1, 0, 0, 0], [-1, -1, -1, 0], [0, 0, 0, 1]],
> [[-1, -1, -1, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [1, 1, 1, 1/4], [0, 0, 0, 1]],
> [[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [0, 0, -1, 1/4], [0, 0, 0, 1]]];;

gap> SG227Left:=AffineCrystGroupOnLeft(GenSG227Left);;

gap> inv2(SG227Left,8) = inv2(SpaceGroupBBNWZ(3, 227),8);
true
```

**Comment by grahamknockillaree** [comment]
Yes, the commands

gap> C:=Classify([1..219],k->inv(k,5));;
gap> C:=RefineClassification(C,k->inv(k,6));;
gap> C:=RefineClassification(C,k->inv(k,7));;
gap> C:=RefineClassification(C,k->inv(k,8));;

have the same mathematical meaning as the single command
 
C:=Classify([1..219],k->inv(k,8));;

But I think you'll find the first commands run faster than the last single command.

As for distinguishing between **isomorphic** space groups that **are not the same up to an affine transformation** of space that preserves orientation,  I don't know how one can use isomorphism invariants to do this. Also, I'm not sure why you would want to, as you already know that SpaceGroupIT(3,k) is distinct from SpaceGroup(3,k') in this sense precisely when k is different to k'.

**Comment by hongyi-zhao** [comment]
> But I think you'll find the first commands run faster than the last single command.

I have also noticed this situation. Why is there such a performance difference?

> Also, I'm not sure why you would want to, as you already know that SpaceGroupIT(3,k) is distinct from SpaceGroup(3,k') in this sense precisely when k is different to k'.

For example, **SpaceGroupIT(3,76)** and **SpaceGroupIT(3,78)** have different generators, as described [here](http://aflowlib.org/prototype-encyclopedia/enantiomorph_info.html), and as shown below:

![image](https://user-images.githubusercontent.com/11155854/178616559-8a720cb1-4d01-4a60-a2a4-fdebe520214b.png)

I want to determine the unique SpaceGroupIT (International Tables for Crystallography) number based on the given generators.

**Comment by grahamknockillaree** [comment]
```gap
gap> C:=Classify([1..219],k->inv(k,5));;
```
calculates (conjugacy classes of) subgroups of index $\le$ 5 for all 219 groups.

```gap
gap> C:=RefineClassification(C,k->inv(k,6));;
```
calculates subgroups of index $\le $ 6 only for those groups that are not fully distinguished by the first command.  And so on.  

The command

```gap
gap> C:=Classify([1..219],k->inv(k,8));;
```
calculates (conjugacy classes of) subgroups of index $\le$ 8 for all 219 groups. Enumerating low-index subgroups is a costly calculation.

By the way, it is sometimes quicker to use G:=SimplifiedFpGroup(G) before calling LowIndexSubgroupsFpGroup(G,d);

The commands

```gap
gap> G76:=SpaceGroupIT(3,76);;
gap> G78:=SpaceGroupIT(3,78);;
gap> L76:=LowIndexSubgroupsFpGroup(Image(IsomorphismFpGroup(G76)),8);;
gap> L76:=SortedList(List(L76,AbelianInvariants));;
gap> L78:=LowIndexSubgroupsFpGroup(Image(IsomorphismFpGroup(G78)),8);;
gap> L78:=SortedList(List(L78,AbelianInvariants));;
gap> L76=L78;
true
```

show that G76 is isomorphic to G78.  However, **I think** the commands

gap> A:=ConjugatorSpaceGroups(G76,G78);;
gap> Determinant(A);
-1

But I am not an expert on space groups.

show that the isomorphism required a non-orientable transformation.

**Comment by hongyi-zhao** [comment]
1. For the isomorphism determination of an arbitrary given 3 dimensional affine crystallographic group `G`, first, use the `RefineClassification` method discussed above to determine which 219 affine class it belongs to. If the result is a list of isomorphism, then use the `ConjugatorSpaceGroups(G,H)` command to test the orientation preserving isomorphism relations between them. The above approach should be more efficient than looping over 230 space groups directly using the `ConjugatorSpaceGroups(G,H)` command, where $H \in SpaceGroupIT(3, x), (1 \le x \le 230)$ .

2. I've checked the eleven pairs of enantiomorphic space groups ([Online Dictionary of Crystallography](http://dictionary.iucr.org/Main_Page), [ITC-A](http://it.iucr.org/Ab/)), as described [here](http://aflowlib.org/prototype-encyclopedia/enantiomorph_info.html):

```gap
gap> enantiomorphic_pairs:=[
>   [76,78],[91,95],[92,96],[144,145],[151,153],
>   [152,154],[169,170],[171,172],[178,179],[180,181],
>   [212,213]
> ];;
gap> conj:=List(enantiomorphic_pairs, x-> ConjugatorSpaceGroups(SpaceGroupIT(3,x[1]) ,SpaceGroupIT(3,x[2])));;
gap> PrintArray(conj);
[ [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],    [ 0, 0, 0, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],    [ 0, 0, 0, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],  [ 0, 0, 1/2, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],    [ 0, 0, 0, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],  [ 0, 0, 1/2, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],    [ 0, 0, 0, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],    [ 0, 0, 0, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],    [ 0, 0, 0, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],  [ 0, 0, 1/2, 1 ] ],
  [   [ -1, 0, 0, 0 ],   [ 0, -1, 0, 0 ],   [ 0, 0, -1, 0 ],  [ 0, 0, 1/2, 1 ] ],
  [   [ 0, -1, 0, 0 ],    [ 0, 0, 1, 0 ],    [ 1, 0, 0, 0 ],  [ 1/2, 0, 0, 1 ] ] ]
gap> List(conj, x-> [TraceMat(x), DeterminantMat(x), Order(x)]);
[ [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ -2, -1, 2 ], [ 1, -1, 6 ] ]
```
I still can't figure out how to identify the isomorphism types between them, say, for this case, enantiomorphic (chiral) isomorphic relationship between them based on the result given by `ConjugatorSpaceGroups`.

**Comment by hongyi-zhao** [comment]
> The following commands, which do not use any HAP functions, show that the abelian invariants of finite index subroups of index less than or equal to 8 suffice to distinguish between the isomorphism types of all 219 space groups.
> 
> ```gap
> gap> inv:=function(k,d)
> > local L,G;
> > G:=SpaceGroup(3,k);;
> > G:=Image(IsomorphismFpGroup(G));;
> > L:=LowIndexSubgroupsFpGroup(G,d);;
> > L:=List(L,AbelianInvariants);;
> > L:=SortedList(L);;
> > return L;;
> > end;;
> gap> C:=Classify([1..219],k->inv(k,5));;
> gap> Length(C);
> 199
> gap> C:=RefineClassification(C,k->inv(k,6));;
> gap> Length(C);
> 213
> gap> C:=RefineClassification(C,k->inv(k,7));;
> gap> Length(C);
> 213
> gap> C:=RefineClassification(C,k->inv(k,8));;
> gap> Length(C);
> 219
> ```

I tried to use the above method as follows, but I got stuck in the penultimate step:

```gap
gap> SGGenSet229me:=[[[0, -1, 0, 1/4], [0, 0, -1, 1/4], [-1, 0, 0, 1/4], [0, 0, 0, 1]],
> [[-1, 2, -1, -3/8], [-3/2, 3/2, -1/2, -1/16], [-1/2, 3/2, -3/2, \
> -17/16], [0, 0, 0, 1]]];
[ [ [ 0, -1, 0, 1/4 ], [ 0, 0, -1, 1/4 ], [ -1, 0, 0, 1/4 ], [ 0, 0, 0, 1 ] ], [ [ -1, 2, -1, -3/8 ], [ -3/2, 3/2, -1/2, -1/16 ], [ -1/2, 3/2, -3/2, -17/16 ], 
      [ 0, 0, 0, 1 ] ] ]
gap> SG229me:=AffineCrystGroupOnLeft(SGGenSet229me);
<matrix group with 2 generators>
gap> LSG229me:=LowIndexSubgroupsFpGroup(SimplifiedFpGroup(Image(IsomorphismFpGroup(SG229me))),8);;
^CError, user interrupt in
  i := i + 2; at /home/werner/Public/repo/github.com/gap-system/gap.git/lib/grpfp.gi:3031 called from 
iter!.IsDoneIterator( iter ) at /home/werner/Public/repo/github.com/gap-system/gap.git/lib/coll.gi:937 called from
IsDoneIterator( iter ) at /home/werner/Public/repo/github.com/gap-system/gap.git/lib/grpfp.gi:3192 called from
LowIndexSubgroupsFpGroup( G, TrivialSubgroup( Parent( G ) ), n ) at /home/werner/Public/repo/github.com/gap-system/gap.git/lib/grpfp.gi:3219 called from
<function "LowIndexSubgroupsFpGroup supply trivial subgroup">( <arguments> )
 called from read-eval loop at *stdin*:28
you can 'return;'
brk> 
gap> SLSG229me:=SortedList(List(LSG229me,AbelianInvariants));
Error, Variable: 'LSG229me' must have a value
not in any function at *stdin*:28
```

**Comment by grahamknockillaree** [comment]
LowIndexSubgroupsFpGroup(G,k) can take a lot of time when k gets large. I tried it your fp group G and it completed in 104 seconds for k=6.  You are trying k=8 and that value of k is very likely is going to take more time and memory.

**Comment by hongyi-zhao** [comment]
Are there any efficient alternative methods to solve this problem?

**Comment by grahamknockillaree** [comment]
As far as I know the GAP implementation of LowIndexSubgroupsFpGroup is as efficient as any.


Graham


School of Mathematical & Statistical Sciences
National University of Ireland, Galway
tel: 091 493011
________________________________

**Comment by hongyi-zhao** [comment]
Are there alternative methods to complete this job using HAP?

**Comment by grahamknockillaree** [comment]
None that I can think of.
