### ISSUE TITLE
Warnings when loading HAP while HAPcryst is not installed

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#76]
Syntax warning: Unbound global variable in /usr/share/gap/pkg/HAP/lib/Polymake/cryst.gi:19
F:=FundamentalDomainStandardSpaceGroup(pt,SAG);;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /usr/share/gap/pkg/HAP/lib/Polymake/cryst.gi:70
st:=OrbitPartInVertexSetsStandardSpaceGroup(G,st,setV);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /usr/share/gap/pkg/HAP/lib/Polymake/cryst.gi:116
g:=RepresentativeActionOnRightOnSets(G,VCells[n+1][kk], VCells[n+1][k]);
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Syntax warning: Unbound global variable in /usr/share/gap/pkg/HAP/lib/Polymake/cryst.gi:154
st:=StabilizerOnSetsStandardSpaceGroup(G,st);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Loading HAP 1.44 ...

The header says it all. Unfortunately HAPcryst depends on HAP.

**Comment by grahamknockillaree** [comment]
Oops!  This was due to a mistake in the read.g file. I've now changed the read.g file from

if IsPackageMarkedForLoading("polymaking","0.0") then
ReadPackageHap( "lib/Polymake/cryst.gi");
fi;

to the intended

if IsPackageMarkedForLoading("HAPcryst","0.0") then
ReadPackageHap( "lib/Polymake/cryst.gi");
fi;

**Comment by narc-Ontakac2** [comment]
Hi.

While looking into this I found a lib witout an l :

Message ID: ***@***.***>
> ################# EDIM COMMANDS #######################################
> if IsPackageMarkedForLoading("edim","1.2.2") then
> ReadPackageHap( "ib/Homology/edim.gi");
> fi;
> #

Sincerely,

Joachim

-- 
Papier ist gebundenes CO2. Bitte drucken Sie diese EMail aus und archivieren Sie sie.
