### ISSUE TITLE
ImageMagick integration broken

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/hap#77]
The following line should display an image, however there are only error messages and an ImageMagick logo is displayed instead:

gap> ViewPureCubicalKnot(PureCubicalKnot(3,1));
convert-im6.q16: pixels are not authentic `/tmp/tm5t8xxk/HAPtmpImage.txt'
@ error/cache.c/QueueAuthenticPixelCacheNexus/4391.
convert-im6.q16: no images defined `/tmp/tm5t8xxk/HAPtmpImage..png' @
error/convert.c/ConvertImageCommand/3229.
display: unable to open image `/tmp/tm5t8xxk/HAPtmpImage.png': No such
file or directory @ error/blob.c/OpenBlob/2924.

The messages can be reproduced by calling convert on the  HAPtmpImage.txt file. 
[HAPtmpImage.txt](https://github.com/gap-packages/hap/files/9083331/HAPtmpImage.txt)

**Comment by narc-Ontakac2** [comment]
I'll look into this. Has anybody encountered the somewhat obscure "pixels are not authentic" message before?

**Comment by grahamknockillaree** [comment]
I've fixed the main problem by uploading a new pureCubicalComplexes.gi file .

The "pixels are not authentic" message still appears and has appeared for a long time. I'm not sure why it appears.

**Comment by narc-Ontakac2** [comment]
The "authentic" message comes from imagemagick starting pixel enumeration at zero.
Changing line 991 by appending -1 to the indexes fixes it:

-AppendTo(filetxt,i,",",j,": ",colour,"\n");
+AppendTo(filetxt,i-1,",",j-1,": ",colour,"\n");

**Comment by grahamknockillaree** [comment]
Many thanks for this. I've uploaded a further modification to pureCubicalComlexes.gi .  I'll close the issue now.
