### ISSUE TITLE
About the example represented in document `7.4 Arithmetic groups`.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#78]
I noticed the following example given in document [`7.4 Arithmetic groups`](https://gap-packages.github.io/hap/tutorial/chap7_mj.html#X7AFFB32587D047FE):

> The following example computes
> 
> $H_{6}\left(S L_{2}(\mathcal{O}, \mathbb{Z})=\mathbb{Z}_{2}\right.$
> 
> for $\mathcal{O}$ the ring of integers of the number field $\mathbb{Q}(\sqrt{-2})$
> 
> ```gap
> gap> C:=ContractibleGcomplex("SL(2,O-2)");;
> gap> R:=FreeGResolution(C,7);;
> gap> Homology(TensorWithIntegers(R),6);
> [ 2, 12 ]
> ```

As you can see, the `Homology` command gives the result `[ 2, 12 ]`, why shouldn't this correspond to `$H_{6}\left(S L_{2}(\mathcal{O}, \mathbb{Z})=\mathbb{Z}_{2} \oplus \mathbb{Z}_{12}$`?

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
Thanks for pointing out this typo.  I've fixed it now.
