### ISSUE TITLE
hap test suite takes a long time; can a quicker one set in PackageInfo.g?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/hap#85]
For the [new GAP package distribution](https://github.com/gap-system/PackageDistro), we are running the test suites of all packages which specify one in their `PackageInfo.g` file. So that includes `hap`, which sets `TestFile := "tst/testall.g"`.

However, this test suite requires 20-25 minutes to complete ([see e.g. here](https://github.com/gap-packages/hap/actions/runs/2768901213), or even more on "bad days", when the GitHub virtual machines are loaded with work and thus slower. Yet for the PackageDistribution, we need to limit how long we run package test suites, as (a) we have ~140 packages to test, and (b) sometimes those run into endless loops or other problems, and we don't want to waste hours of CPU time waiting for them to (not) finish.

Thus it would be super helpful if the hap test suite either was faster; or was split into a "fast" and a "full" version. Then the CI here on the repository could keep running the full test suite, via `tst/testall.g`; but a separate file, say `tst/testquick.g` could be added which only executes some of the tests, and which is used for the `TestFile` component in `PackageInfo.g`

**Comment by grahamknockillaree** [comment]
I've been meaning to reduce the time taken by the the testall.g for some time now! I'll get to work on doing this soon.  

A few of the tests take well over five seconds -- I can initially make a testquick.g file that simply doesn't call these slow tests.  Then I can fiddle to see if changing parameters in the slow tests helps to reduce the time taken by testall.g.

**Comment by grahamknockillaree** [comment]
@fingolfin I've added a testquick.g file and changed PackageInfo.g so that it now calls testquick.g rather than testall.g. On my laptop testquick.g take 95 seconds.
```total     95335 ms (14020 ms GC) and 11.0GB allocated
              0 failures in 82 files

#I  No errors detected while testing```
This is much faster on my laptop than the old testall.g. Unfortunately, on github  testquick.g  doesn't give much of a speed up - it still takes 25 minutes. I can't understand why.
   
The testquick.g file has 42% code coverage compared to the old testall.g which had 55% code coverage.  I've now added some slow tests to testall.g so that it will take even longer than before but should have better code coverage.

**Comment by grahamknockillaree** [comment]
The new testall.g file takes 33 minutes on my laptop
```
total   1994984 ms (209871 ms GC) and 421GB allocated
              0 failures in 114 files

#I  No errors detected while testing
```
compared to the 74 seconds taken by the new testquick.g . 
```
total     74829 ms (12610 ms GC) and 11.0GB allocated
              0 failures in 82 files

#I  No errors detected while testing
```

 For some reason though, they both take similar times to run on github.  I have absolutely no idea why!?

For the moment I'll point PackageInfo.g to testquick.g as the default test for HAP.

**Comment by fingolfin** [comment]
Thank you, I can confirm this works, and look forward to the next `hap` release then (which is *not* urgent from my point of view; I am just happy to see one more red "failure" symbol turn into a green checkmark ;-) ).

As to this:
> For some reason though, they both take similar times to run on github. I have absolutely no idea why!?

I am not sure what you mean? How did you test this?

**Comment by grahamknockillaree** [comment]
>I am not sure what you mean? How did you test this?

The setting  Test := testquick.g  in PackageInfo.g specifies which files github tests.

But I now realize why githib was taking so long on testquick.g. I had forgotten to remove duplicate copies of some tests in github. That is now fixed and quicketst.g takes 8 minutes on github.
