### ISSUE TITLE
Why check for "x86_64-pc-linux-gnu-default64"

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/hap#87]
I am confused as to why `tst/testall.g` and other places perform checks like `StartsWith(GAPInfo.Architecture,"x86_64-pc-linux-gnu-default64")`.

This is rather strange, and I wonder what kind of platform specific thing your code does that means it couldn't run on e.g. my M1 Mac?

**Comment by fingolfin** [comment]
On #83 you seem to indicate that you want to test for a 64 bit system. If so, please instead test for `GAPInfo.BytesPerVariable = 8` -- or possibly `GAPInfo.BytesPerVariable >= 8` depending on what you *really* want to test for. All in all it is still not clear to me what specific issue there is with 32bit systems these tests are meant to deal with? Perhaps adding a comment next to the checks which explains why they are there would be a good idea?

I've also noticed a test `if (GAPInfo.Version{[1..4]}="4.11" or GAPInfo.Version{[1..4]}="4.12") then` which also is problematic. Again based on what you write in #83 it seems you may want to test for "GAP >= 4.11" here? But the above test will fail in GAP 4.13... This is why we have `CompareVersionNumbers`. But I assume you are not using it because of the pesky "dev" in `GAPInfo.Version` when run under GAP development versions, which would make your test fail *in the CI* in GAP 4.10 and older, as we run dev versions there, too (something we should fix *sigh*, see https://github.com/gap-actions/setup-gap/issues/24).

Anyway, this here should be a more robust alternative check:
```
  # Verify GAP >= 4.11
  if CompareVersionNumbers(ReplacedString(GAPInfo.Version, "dev", ""), "4.11") then
    ...
  fi;
```

**Comment by grahamknockillaree** [comment]
I've made these changes to testall.g and testquick.g .  Thanks again!
