### ISSUE TITLE
The relationship between group homology and Smith Normal Form.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/hap#91]
I've noticed that there are inextricable connections between the group homology and Smith Normal Form. But I did not have a clear understanding of this issue. I wonder if the HAP package has some functions in this area or uses related principles.

Regards,
Zhao

**Comment by grahamknockillaree** [comment]
HAP uses the following "homology pipeline".

1. Input data (which could be a group $G$, a data set $S$, a knot or knotted surface $k$, a simplicial complex $K$, ...).
2. Construct a regular CW-complex $X$ which is somehow mathematically associated to the input. (For a group $G$ the space $X=B(G)$ is a classifying space, for a knot $k\subset S^3$ the CW-complex  $X$ is homeomorphic to $S^3\setminus k$, for a simplicial complex $K$ the CW-complex $X$ simply forgets that the cell structure on $K$ is simplicial, for a data set $S$ the space $X$ is the CW-complex obtained from an associated simplicial or cubical space, ...)
3. Construct an admissible discrete vector field on $X$ representing a homotopy equivalence $X \simeq Y$ where $Y$ is a typically non-regular and smaller CW-complex.
4. Construct the cellular chain complex $C_\ast Y$ in which the boundary homomorphisms $C_nY\rightarrow C_{n-1}Y$ are represented by integer matrices.
5. Compute the $n$-th integral homology $H_n(input) = H_n(C_\ast Y) = ker(C_nY \rightarrow C_{n-1}Y)  / image(C_{n+1}Y \rightarrow C_nY)$.

In the final Step 5 a basis for $ker(C_nY \rightarrow C_{n-1}Y)$ is computed using gaussian elimination over the rationals. A basis for $image(C_{n+1}Y \rightarrow C_nY)$ is computed using GAP's **Smith Normal Form algorithm**.

**Comment by hongyi-zhao** [comment]
The following is the background I raised this question: Whether **Smith Normal Form  (SNF)** can give some implicit information of constructing the minimum generating set of a space group.

See for following example:

```Mathematica
In[136]:= SGGenSetITA227O1
SGGenSetITA227O1[[{4,6,2}]]//AMTCrystGroupOnLeft//First//Length
SGGenSetITA227O1[[{4,6,3}]]//AMTCrystGroupOnLeft//First//Length
SGGenSetITA227O1[[{4,6,5}]]//AMTCrystGroupOnLeft//First//Length
SGGenSetITA227O1[[{4,6,7}]]//AMTCrystGroupOnLeft//First//Length
SGGenSetITA227O1[[{4,6,8}]]//AMTCrystGroupOnLeft//First//Length

Out[136]= {{{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, 0, 
   1}}, {{-1, 0, 0, 1}, {0, -1, 0, 1/2}, {0, 0, 1, 1/2}, {0, 0, 0, 
   1}}, {{-1, 0, 0, 1/2}, {0, 1, 0, 1/2}, {0, 0, -1, 1}, {0, 0, 0, 
   1}}, {{0, 0, 1, 0}, {1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 0, 1}}, {{0,
    1, 0, 3/4}, {1, 0, 0, 1/4}, {0, 0, -1, 3/4}, {0, 0, 0, 1}}, {{-1, 
   0, 0, 1/4}, {0, -1, 0, 1/4}, {0, 0, -1, 1/4}, {0, 0, 0, 1}}, {{1, 
   0, 0, 0}, {0, 1, 0, 1/2}, {0, 0, 1, 1/2}, {0, 0, 0, 1}}, {{1, 0, 0,
    1/2}, {0, 1, 0, 0}, {0, 0, 1, 1/2}, {0, 0, 0, 1}}}

Out[137]= 96

Out[138]= 96

Out[139]= 192

Out[140]= 24

Out[141]= 24
```
![image](https://user-images.githubusercontent.com/11155854/188881387-8bc10b97-9915-4c25-8f59-1f7b7e5b61ba.png)

As you can see, in the above example, only the combinations of the elements 4, 5, 6 can generate the full original space group. Therefore, I want to get some useful criterion information from the form of SNF. I wonder if you have any experience or knowledge in this field.

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
My intuition comes from the following (possibly wrong) understanding: In the space group case, if a generator has a smaller translation component, it may generate more group elements. On the other hand, the form of SNF is directly related to the translation group of the space group. Therefore, I think that the SNF form with a smaller value in the upper left corner of the main diagonal may be a candidate to constitute the minimum generating set.

**Comment by grahamknockillaree** [comment]
Consider the group G generated by the three matrices

A=[ [    1,    0,    0 ],
       [    0,   -1,    0 ],
       [  1/2,    0,    1 ] ]

B=[ [  1,  0,  0 ],
       [  0,  1,  0 ],
       [  1,  0,  1 ] ]

C:=[ [  1,  0,  0 ],
        [  0,  1,  0 ],
        [  0,  1,  1 ] ]

How do you use Smith Normal Form to prove that G is in fact generated by just A and C?

**Comment by hongyi-zhao** [comment]
```Mathematica
"a:=[ [ 1, 0, 0 ],
[ 0, -1, 0 ],
[ 1/2, 0, 1 ] ];"//StringReplace[#,{"\n "->"","["->"{","]"->"}",":="->"=",";"->""}]&//ToExpression;

"b:=[ [ 1, 0, 0 ],
[ 0, 1, 0 ],
[ 1, 0, 1 ] ];"//StringReplace[#,{"\n "->"","["->"{","]"->"}",":="->"=",";"->""}]&//ToExpression;

"c:=[ [ 1, 0, 0 ],
[ 0, 1, 0 ],
[ 0, 1, 1 ] ];"//StringReplace[#,{"\n "->"","["->"{","]"->"}",":="->"=",";"->""}]&//ToExpression;

MatrixForm/@#&/@(SmithDecomposition/@{a,b,c})//Grid
```
![image](https://user-images.githubusercontent.com/11155854/189001444-ac541c4d-200e-4ffc-a4ba-a1c78312b4df.png)

As you can see, `b` and `c` have the exactly same SNF, so, in my logic, they should have the similar capability in generating the group. That is, `a` and `b` or `a` and `c` should generate the same group.

But it is worth noting that the above example is an unimodular infinity matrix group. But my case is space group, which only allow specific unimodular matrices as the point group operations according to the [Crystallographic restriction theorem](https://en.wikipedia.org/wiki/Crystallographic_restriction_theorem), and I further apply the modulo 1 on the translation vector part of the space group elements, as a result, the ultimate group is finite.

**Comment by grahamknockillaree** [comment]
Does the same reasoning suggest that the group G is also generated by just the two matrices A and B?

**Comment by hongyi-zhao** [comment]
Considering that Mathematica's command begins with a capital letter, so I changed your variable names A, B, C, to a, b, c, respectively, to denote the same matrices. They are the exactly same thing. 

But, to be frank, all the above reasoning just my conjecture without any exact evidence and proof.

**Comment by grahamknockillaree** [comment]
A and B (or a and b) do not generate the group G=<A,B,C>.  So, I still don't see how SNF can be used to find  a minimal generating set for this particular group G.  I do see how SNF could be used to prove that the group <A,B> is not equal to G.

**Comment by hongyi-zhao** [comment]
> I do see how SNF could be used to prove that the group <A,B> is not equal to G.

How did you prove it?

**Comment by grahamknockillaree** [comment]
SNF could certainly be used to compute $G_{ab}=\mathbb Z_2\oplus \mathbb Z$. Then **perhaps** one could show that the images of $A$ and $B$ in $G_ab$ do not generate $G_{ab}$. However, I've not actually worked out this latter calculation so I'm not claiming it for certain.

**Comment by hongyi-zhao** [comment]
> SNF could certainly be used to compute $G_{ab}=\mathbb Z_2\oplus \mathbb Z$.

What is the code snippet from which you infer this conclusion?

**Comment by grahamknockillaree** [comment]
gap> GroupHomology(SpaceGroup(2,4),1);
[ 2, 0 ]

**Comment by hongyi-zhao** [comment]
See my following testing:
```gap
gap> A:=[ [ 1, 0, 0 ],
> [ 0, -1, 0 ],
> [ 1/2, 0, 1 ] ];
[ [ 1, 0, 0 ], [ 0, -1, 0 ], [ 1/2, 0, 1 ] ]
gap> 
gap> B:=[ [ 1, 0, 0 ],
> [ 0, 1, 0 ],
> [ 1, 0, 1 ] ];
[ [ 1, 0, 0 ], [ 0, 1, 0 ], [ 1, 0, 1 ] ]
gap> Gab:=Group(A,B);
Group([ [ [ 1, 0, 0 ], [ 0, -1, 0 ], [ 1/2, 0, 1 ] ], [ [ 1, 0, 0 ], [ 0, 1, 0 ], [ 1, 0, 1 ] ] ])
gap> LoadPackage("hap");
true
gap> GroupHomology(SpaceGroup(2,4),1);
[ 2, 0 ]
gap> GroupHomology(Gab,1);
Error, Function Calls: <func> must return a value in
  GroupCohomologyOriginal(  ) at /home/werner/Public/repo/github.com/gap-system/gap.git/pkg/hap/lib/Homology/groupHomology.gi:305 called from 
<function "GroupHomology">( <arguments> )
 called from read-eval loop at *stdin*:28
type 'quit;' to quit to outer loop
```
Why did the last command fail?

**Comment by hongyi-zhao** [comment]
My further attempts and summary are as follows.

1. All the following commands failed:

```gap
IsomorphismPcGroup(Gab);
IsomorphismFpGroup(Gab);
Pcgs(Gab);
AbelianInvariants(Gab);
```
2. The following method works:

```gap
gap> Image(IsomorphismPcpGroup(Gab));
Pcp-group with orders [ 2, 0 ]
gap> GroupHomology(last,1);
[ 0 ]
gap> GroupHomology(SpaceGroup(2,4),1);
[ 2, 0 ]
```
But the GroupHomology's results are not the same.

**Comment by grahamknockillaree** [comment]
They are not the same because Gab is not equal to SpaceGroup(2,4).  For instance, the latter is not abelian.

**Comment by hongyi-zhao** [comment]
But the following information should indicate that it's isomorphic to `SpaceGroup(2,4)`, am I right?
```gap
gap> Image(IsomorphismPcpGroup(Gab));
Pcp-group with orders [ 2, 0 ]
```

**Comment by grahamknockillaree** [comment]
No. SpaceGroup(2,4) is NOT abelian.
