### ISSUE TITLE
Possible transfer of SignRat to Utils 

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/hap#96]
GAP issue #5191 has raised the question of needing to load HAP(Cryst?) to use SignRat. 
This appears to be a suitable case of transferring a utility function to Utils. 
If you approve I can get the process started.

**Comment by grahamknockillaree** [comment]
It seems a good idea to move SignRat to Utils.

**Comment by cdwensley** [comment]
Hi Graham

Sorry to have bothered you about this.
Max has recommended adding a Sign function to the main GAP library as an 
alternative solution,
so I will close the issue.

Cheers, Chris
